name: PixCore
version: '1.0'
main: com.pixra.pixCore.PixCore
api-version: '1.21'
softdepend: [StrikePractice, PlaceholderAPI]
commands:
  pix:
    description: PixCore admin commands
    usage: /pix <reload|pl|bed|leaderboard>
    permission: pixcore.admin
  savelayout:
    description: Save custom layouts manually created while in battle.
    aliases: [ layout, savekit ]
  leaderboard:
    description: Leaderboard
    usage: /leaderboard
    aliases: [lb]
  l:
    description: Leave the current match (short alias for /leavematch)
    usage: /l
  party:
    description: Party commands (redirects to StrikePractice party)
    usage: /party <create|invite|join|kick|leave|disband|info|chat|fight>